#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tek kaynaktan (assets/tanim.json) türev dosyaları üretir:
  references/bolumler-*.md · references/yazim.md · references/denetim.md · assets/icerik-semasi.json · SKILL.md içindeki SEKIL bloğu
Kullanım: python scripts/derle.py            (yazar)
          python scripts/derle.py --kontrol  (yalnız fark denetler; fark varsa 1 döner)
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bv  # noqa: E402

T, KOK = bv.T, bv.KOK
BAS, SON = "<!-- BEGIN:SEKIL (generated by scripts/derle.py from assets/tanim.json - do not edit by hand) -->", "<!-- END:SEKIL -->"
DOSYA_GRUPLARI = [("bolumler-1-2.md", ["1", "2"], "Genel ve Fonksiyonel"), ("bolumler-3.md", ["3"], "Teknik"),
                  ("bolumler-4-5.md", ["4", "5"], "SAP Nesneleri, Hata ve Yetki"), ("bolumler-6-7.md", ["6", "7"], "Test ve İşletim")]


def bolum_dosyasi(gruplar, ad):
    out = [f"# Bölüm yazım bilgisi · {ad}", "",
           "Üretilmiş dosyadır (kaynak: assets/tanim.json). Sütun numaraları 0'dan başlar ve JSON'daki dizi sırasıdır. "
           "{X-nn} satır kimliğidir; [a | b] yalnız bu değerleri alır; (KARAR) = kararı sen verme, girdide yoksa işaretle.", ""]
    for b in T["bolumler"]:
        if b["grup"] in gruplar:
            out += [bv.bilgi_metni(b, ornek=True), "İyi pratik: " + b["pratik"], ""]
    return "\n".join(out).rstrip() + "\n"


def yazim():
    out = ["# Yazım kuralları", "", "Üretilmiş dosyadır (kaynak: assets/tanim.json).", "",
           "## Hücre ve kimlik kuralları", "",
           "- Her hücre boş olmayan bir metindir; değer yoksa `—` yazılır.",
           "- Kimlik `ÖNEK-nn` biçimindedir, iki hanelidir ve belge genelinde tekildir.",
           "- Birden çok kimlik virgülle tek tek yazılır: `STEP-01, STEP-02`. Aralık (`STEP-01…06`) geçersizdir.",
           "- Bir bölüm başka bölüme yalnız kimlikle atıf yapar. Zincir: REQ → SC → STEP → OBJ / MAP / MSG → TC.",
           "- 3.5'te eşleme kullanan adım MAP kimliklerini, hata veren adım MSG kimliğini anar; 4.1 'Kullanıldığı yer' STEP / MAP / UI kimliklerini anar. "
           "6.2 bu atıflardan türetilir.", "",
           "## İşaretler", "",
           f"- Eksik karar: `{T['isaretler']['karar']} (OPEN-nn)` · eksik bilgi: `{T['isaretler']['bilgi']} (OPEN-nn)`. Seçenekli sütunlar da işaret alabilir. "
           "Bilinmeyen bir olgu varsayılan bir değerle (`Hayır`, `Must`, uydurma tarih) doldurulmaz.",
           "- 7.3 satırı işaret içermez. Sahip: ad, bilinmiyorsa rol. Hedef tarih: verilmişse; yoksa `—`, uydurulmaz. Durum `Açık`. "
           "KARAR işaretinin andığı satırın kategorisi `Karar bekleyen konu` olur; diğerlerinde uygun hazırlık kalemi ya da `—`.",
           "- Aynı soruya bağlı karar ve bilgi işaretleri tek bir OPEN-nn paylaşabilir; satırın kategorisi o zaman `Karar bekleyen konu` olur.",
           "- Hücrenin bilinen kısmı yazılır, yalnız bilinmeyen kısmı işaret alır: `HTTP POST; zaman aşımı KARAR BEKLİYOR (OPEN-03)`.",
           "- Geçersiz kılınamayan bir bölümün tamamı tek bir kararı bekliyorsa en az satır sayısı kadar satır yazılır; bilinen hücreler metin, "
           "karara bağlı hücreler işaret olur. İşaretli satır çoğaltılmaz.",
           f"- Girdide ve proje kataloğunda olmayan SAP standart nesne adı yalnız 4.1'de adın sonuna ` {T['isaretler']['dogrula']}` eklenerek yazılır; "
           "bu adların tümü için 7.3'te tek bir açık nokta açılır.",
           "- Özel (Z/Y) adlar projenin adlandırma kuralına göre önerilebilir.", "",
           "## Hazırlık cezası kategorileri (7.3)", "", "| Kategori | Ne zaman |", "|---|---|"]
    out += [f"| {k} | {T['hazirlik_anlamlari'][k]} |" for k in T["hazirlik_kalemleri"]]
    out += ["| — | Hiçbiri uymuyor (örneğin yalnız bir tarih ya da sorumlu adı bekleniyor) |", "",
           "## EARS gereksinim kalıpları (2.2)", "", "| Kalıp | Söz dizimi | Örnek |", "|---|---|---|"]
    out += [f"| {e['kalip']} | {e['soz_dizimi']} | {e['ornek']} |" for e in T["ears"]]
    out += ["", "Kabul kriteri Given – When – Then biçimindedir: ön koşul ve test verisi · tetikleyen olay · gözlenebilir sonuç ve nerede gözlendiği.", "",
            "## Yuvarlak ifade yerine somut karşılık", "", "| Yazma | Bunun yerine |", "|---|---|"]
    out += [f"| {x['yazma']} | {x['yaz']} |" for x in T["yuvarlak_karsiliklar"]]
    out += ["", "Denetimin aradığı kalıplar: " + ", ".join(f"`{x.strip()}`" for x in T["yuvarlak_ifadeler"]) + ".", "",
            "## Somutluk", "",
            "- Sıfat yerine ölçü: süre, adet, hacim, saklama süresi, tekrar sayısı sayıyla ve birimiyle yazılır.",
            "- Nesne ve alan adı yazılır: `I_PurchaseOrderAPI01.PurchaseOrder`; 'ilgili tablo' yazılmaz.",
            "- Test verisi gerçek biçimlidir: belge numarası, ana veri numarası, şirket kodu.",
            "- RAP'te kalıcılık save sequence içinde olur; `COMMIT WORK` yazılmaz."]
    return "\n".join(out) + "\n"


def denetim():
    P = T["parametreler"]
    out = ["# Mekanik denetim ve gösterge", "", "Üretilmiş dosyadır (kaynak: assets/tanim.json). Kod çalıştırılabiliyorsa `scripts/bv.py denetle` yetkilidir; "
           "çalıştırılamıyorsa aşağıdaki liste elle uygulanır.", "",
           "## Puanlama motorunun kuralları (mekanik karşılıkları)", "", "| Kural | Ne ister | Ağırlık | Şiddet | Bölüm |", "|---|---|---|---|---|"]
    out += [f"| {k['id']} | {k['baslik']} | {k['agirlik']} | {k['siddet']} | {'tümü' if k['bolumler'] == ['*'] else ', '.join(k['bolumler'])} |" for k in T["kurallar"]]
    out += ["", "Eski motor kuralları (ayrıca raporlanır, göstergeye girmez): " + " · ".join(f"{k['id']} {k['baslik']} ({k['bolum']})" for k in T["eski_kurallar"]) + ".", "",
            "## Skill'in kendi denetimleri", "",
            "| Kural | Önem | Ne denetler |", "|---|---|---|",
            "| YAPI_001–009 | hata / uyarı | Şema sürümü, tür ve profil, tanımsız bölüm ya da alan, satır uzunluğu, seçenek değerleri, kimlik biçimi, yinelenen kimlik |",
            "| KRITIK_001 | hata | Kritik bölüm elle geçersiz kılınamaz |",
            "| ZINCIR_001 | hata | Anılan her kimlik tanımlı olmalı |",
            "| ZINCIR_002 | uyarı | Her REQ'in en az bir SC, STEP ve TC'si olmalı |",
            "| UYD_001 | hata | SAP standart nesne adı girdide ya da proje kataloğunda olmalı ya da `[DOĞRULANACAK]` ile işaretlenmeli |",
            "| UYD_002 | uyarı | Doğrulanacak nesneler için 7.3'te açık nokta olmalı |",
            "| KARAR_001 | uyarı | BEKLİYOR işareti bir OPEN-nn taşımalı |",
            "| KARAR_002 | uyarı | KARAR işaretinin andığı açık noktanın hazırlık kategorisi olmalı |",
            "| OPEN_001 | uyarı / bilgi | Açık noktanın sahibi olmalı (ad ya da rol; kusur). Hedef tarihi olmayan satırlar girdi bekleyen olarak sayılır |",
            "| OPEN_002 | uyarı | 7.3 'Etkilediği bölüm' bu belgede geçerli bölüm numaraları içermeli |",
            "| ZINCIR_003 | bilgi | E ve A tipindeki her mesajın bir test senaryosu olmalı |",
            "| YAPI_010 | uyarı | meta, surum_gecmisi ve onaylar hücreleri dolu olmalı (yoksa —) |", "",
            "## Kusur ve girdi bekleyen", "",
            "`denetle` iki tür sonuç verir. **Kusur**: yazımdan doğan, düzeltilmesi gereken bulgu. **Girdi bekleyen**: kural yalnız bir hücre karar ya da bilgi "
            "beklediği için kalır; gösterge bunu sayar ama düzeltilecek bir şey yoktur, içerik uydurulmaz. Çıkış kodu yalnız kusur düzeyindeki hatada 1 olur.", "",
            "## Elle kontrol listesi (kod çalıştırılamıyorsa)", "",
            "1. `«…»`, TBD, TODO, boş hücre yok; yoksa `—`.", "2. 2.5'te Bağımlılık, Varsayım, Kapsam dışı üçü de var; kapsam sınırı yazılı.",
            "3. 2.1'de 'Evet' işaretli sorunlu adım ve sayısal etkisi var.", "4. 2.2 ve 3.5'te yuvarlak ifade yok.",
            "5. 3.5 en az 3 adım; adımların çoğu SAP nesnesi adı içeriyor; hata → MSG ve commit/rollback yazılı.",
            "6. 3.4'te her satırda kaynak, hedef, tip, örnek değer dolu.", "7. 5.1 en az 2 satır; tip E/W/I/S/A.",
            "8. 6.1 en az 2 senaryo; en az biri Negatif ya da Sınır; test verisinde gerçek biçimli numara var.",
            "9. 5.2 / 5.3 satırlarında nesne, alan-değer, aktivite, katalog adları dolu.",
            "10. Başka bölümlerde geçen her nesne adı 4.1'de; 4.1'deki her ad başka bir bölümde geçiyor; tip listeden; Z adları kurala uygun.",
            "11. Anılan her kimlik tanımlı; her REQ'in SC, STEP ve TC'si var.",
            "12. Her BEKLİYOR işareti ve her `[DOĞRULANACAK]` bir 7.3 satırına bağlı; açık satırların sahibi (ad ya da rol) ve etkilediği bölüm numaraları var.", "",
            "## Gösterge", "",
            "Yalnız mekanik kurallardan hesaplanır; kalite (LLM) puanını gerçek motor ölçer. Hedef değil, yan üründür.", "",
            f"- Bölüm kural puanı = 100 × (1 − kalan kural ağırlığı / değerlendirilen kural ağırlığı); `info` kuralı × {P['info_factor']}; "
            f"`error` kuralı kaldıysa en çok {P['error_cap']}.",
            "- Ortalama = ağırlıklı ortalama; geçerli taban bölümler ve yazılmış bonus bölümler.",
            f"- Cezalar: puanı {P['crit_thr']}'ın altındaki her kritik bölüm −{P['crit_pen']}; en düşük 2 taban bölüm ortalamanın {P['weak_gap1']}+ altındaysa "
            f"−{P['weak_pen1']}, {P['weak_gap2']}+ altındaysa −{P['weak_pen2']} (en çok −{P['weak_cap']}); 7.3'te kategorili her açık nokta −{P['ready_per']} "
            f"(kalem başına en çok −{P['ready_item_cap']}, toplam en çok −{P['ready_cap']}).",
            f"- Bantlar: ≥ {P['band_hi']} Geliştirmeye hazır · {P['band_mid']}–{P['band_hi'] - 1} Koşullu · < {P['band_mid']} Revizyon.",
            "- " + T["parametre_notu"]]
    return "\n".join(out) + "\n"


def sema():
    isaret = {"type": "string", "pattern": "BEKLİYOR"}
    bolumler = {}
    for b in T["bolumler"]:
        if b.get("turetilmis"):
            continue
        dolu = {"type": "object", "additionalProperties": False, "properties": {"mermaid": {"type": "string"}}}
        if b["alanlar"]:
            dolu["properties"]["alanlar"] = {"type": "object", "additionalProperties": False, "required": [a["anahtar"] for a in b["alanlar"]],
                                            "properties": {a["anahtar"]: {"type": "string", "minLength": 1} for a in b["alanlar"]}}
            dolu["required"] = ["alanlar"]
        if b["sutunlar"]:
            ogeler = []
            for c in b["sutunlar"]:
                if c.get("secenekler"):
                    ogeler.append({"anyOf": [{"enum": c["secenekler"]}, isaret]})
                elif c.get("kimlik"):
                    ogeler.append({"type": "string", "pattern": "^(" + "|".join(c["kimlik"]) + ")-[0-9]{2,3}$"})
                else:
                    ogeler.append({"type": "string", "minLength": 1})
            dolu["properties"]["satirlar"] = {"type": "array", "minItems": b["en_az_satir"],
                                             "items": {"type": "array", "items": ogeler, "minItems": len(ogeler), "maxItems": len(ogeler)}}
            dolu.setdefault("required", []).append("satirlar")
        gecersiz = {"type": "object", "additionalProperties": False, "required": ["gecerli", "gerekce"],
                    "properties": {"gecerli": {"const": False}, "gerekce": {"type": "string", "minLength": 1}}}
        bolumler[b["no"]] = dolu if b["sinif"] == "Kritik" else {"oneOf": [dolu, gecersiz]}
    dizi = lambda n: {"type": "array", "items": {"type": "array", "items": {"type": "string"}, "minItems": n, "maxItems": n}}
    return {"$schema": "http://json-schema.org/draft-07/schema#", "title": "Belirtim Yazmanı FS-TS içeriği", "type": "object",
            "required": ["sema", "meta", "turler", "profil", "bolumler"], "additionalProperties": False,
            "properties": {"sema": {"const": T["sema"]},
                           "meta": {"type": "object", "required": ["surum", "tarih", "hazirlayan", "durum"],
                                    "properties": {k: {"type": "string"} for k in ("surum", "tarih", "hazirlayan", "durum", "musteri")}},
                           "turler": {"type": "array", "minItems": 1, "uniqueItems": True, "items": {"enum": [t["kod"] for t in T["tur_tanimlari"]]}},
                           "profil": {"enum": list(T["profiller"])},
                           "bolumler": {"type": "object", "additionalProperties": False, "properties": bolumler},
                           "surum_gecmisi": dizi(4), "onaylar": dizi(3), "nesne_degil": {"type": "array", "items": {"type": "string"}}}}


SEKIL_METIN = {
    "en": {"legend": "Legend: `no title | weight class | types | fields | columns`. Class K = Kritik, N = Normal, B = Bonus (bonus sections open by profile). "
                     "Types: {turler}; `*` = all. "
                     "Column 0 written as `{{X}}` is the row ID `X-nn`; `{{A/B/C}}` = one of these prefixes, by row kind. `[a|b]` after a column = only these values; "
                     "after a field = preferred wording (when none fits, write the stated decision in its own words). "
                     "`†` = a decision: write it only when the inputs state it or a stated decision determines it completely; otherwise a KARAR marker.",
           "derived": "derived by the script - never write", "min": " (min {n} rows)", "all": "all", "tam": "tam only",
           "bonus": "Bonus sections opened in profile `standart`: {liste}. Profile `hafif` opens only 6.2; `tam` opens all.",
           "n54": "5.4 lists only the extra columns; message class, type and TR text are joined from 5.1 by MSG id.",
           "n34": "5.2 and 5.3 share one AUTH sequence. 3.4 for type U without an external interface maps source (CDS / API field) to service entity property: "
                  "`yon` and `comm_scenario` are `—`, `protokol` is the OData version of 1.2, `tetikleyici` is the user action."},
    "tr": {"legend": "Gösterim: `no başlık | ağırlık sınıf | türler | alanlar | sütunlar`. Sınıf K = Kritik, N = Normal, B = Bonus (bonus bölümleri profil açar). "
                     "Türler: {turler}; `*` = tümü. "
                     "`{{X}}` biçimindeki 0. sütun `X-nn` satır kimliğidir; `{{A/B/C}}` = satırın türüne göre bu öneklerden biri. Sütundan sonraki `[a|b]` = yalnız bu değerler; "
                     "alandan sonraki = tercih edilen ifade (hiçbiri uymuyorsa verilen kararı kendi sözleriyle yaz). "
                     "`†` = karar: yalnız girdi söylüyorsa ya da söylenen bir karar onu tümüyle belirliyorsa yaz; aksi halde KARAR işareti.",
           "derived": "betik türetir - asla yazma", "min": " (en az {n} satır)", "all": "tümü", "tam": "yalnız tam",
           "bonus": "`standart` profilde açılan bonus bölümler: {liste}. `hafif` profil yalnız 6.2'yi, `tam` hepsini açar.",
           "n54": "5.4'te yalnız ek sütunlar yazılır; mesaj sınıfı, tip ve TR metin MSG kimliğiyle 5.1'den birleştirilir.",
           "n34": "5.2 ve 5.3 tek bir AUTH sırasını paylaşır. Dış arayüzü olmayan U türünde 3.4, kaynağı (CDS / API alanı) servis entity property'sine eşler: "
                  "`yon` ve `comm_scenario` `—`, `protokol` 1.2'deki OData versiyonu, `tetikleyici` kullanıcı eylemidir."},
}


def sekil(dil="en"):
    M = SEKIL_METIN.get(dil, SEKIL_METIN["en"])
    out = [BAS, M["legend"].format(turler=", ".join(f"{t['kod']} = {t['ad']}" for t in T["tur_tanimlari"])), ""]
    for b in T["bolumler"]:
        alanlar = ", ".join(a["anahtar"] + ("†" if a.get("karar") else "") + (" [" + "|".join(a["secenekler"]) + "]" if a.get("secenekler") else "")
                            for a in b["alanlar"]) or "—"
        if b.get("turetilmis"):
            sutunlar = M["derived"]
        elif not b["sutunlar"]:
            sutunlar = "—"
        else:
            sutunlar = "; ".join(("{" + "/".join(c["kimlik"]) + "}" if c.get("kimlik") else c["ad"])
                                 + (" [" + "|".join(c["secenekler"]) + "]" if c.get("secenekler") else "") + ("†" if c.get("karar") else "")
                                 for c in b["sutunlar"])
        ek = M["min"].format(n=b["en_az_satir"]) if b["en_az_satir"] > 1 else ""
        out.append(f"{b['no']} {b['baslik']} | {b['agirlik']} {b['sinif'][0]} | {','.join(b['turler'])} | {alanlar} | {sutunlar}{ek}")
    liste = ", ".join(f"{b['no']} ({M['all'] if '*' in b['bonus_acilis'] else '/'.join(b['bonus_acilis']) or M['tam']})"
                      for b in T["bolumler"] if b["sinif"] == "Bonus")
    out += ["", M["bonus"].format(liste=liste), M["n54"], M["n34"], SON]
    return "\n".join(out)


def hedefler():
    h = {os.path.join("references", d): bolum_dosyasi(g, ad) for d, g, ad in DOSYA_GRUPLARI}
    h[os.path.join("references", "yazim.md")] = yazim()
    h[os.path.join("references", "denetim.md")] = denetim()
    h[os.path.join("assets", "icerik-semasi.json")] = json.dumps(sema(), ensure_ascii=False, indent=1) + "\n"
    skill = os.path.join(KOK, "SKILL.md")
    if os.path.exists(skill):
        s = open(skill, encoding="utf-8").read()
        if BAS in s and SON in s:
            dil = re.search(r'(?m)^\s*language:\s*"?(tr|en)"?\s*$', s[:s.index(BAS)])
            h["SKILL.md"] = s[:s.index(BAS)] + sekil(dil.group(1) if dil else "en") + s[s.index(SON) + len(SON):]
    return h


def main():
    kontrol = "--kontrol" in sys.argv
    fark = []
    for yol, icerik in hedefler().items():
        tam = os.path.join(KOK, yol)
        mevcut = open(tam, encoding="utf-8").read() if os.path.exists(tam) else None
        if mevcut != icerik:
            fark.append(yol)
            if not kontrol:
                os.makedirs(os.path.dirname(tam), exist_ok=True)
                with open(tam, "w", encoding="utf-8") as f:
                    f.write(icerik)
    if kontrol:
        print("Türev dosyalar güncel." if not fark else "Güncel değil: " + ", ".join(fark) + " → python scripts/derle.py")
        sys.exit(1 if fark else 0)
    print("Yazıldı: " + (", ".join(fark) if fark else "değişiklik yok"))


if __name__ == "__main__":
    main()
