#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generates the derived files from the single source (assets/tanim.json):
  references/bolumler-*.md · references/yazim.md · references/denetim.md · assets/icerik-semasi.json · the SEKIL block inside SKILL.md
Usage: python scripts/derle.py            (writes)
       python scripts/derle.py --kontrol  (checks for drift only; exits 1 on drift)
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bv  # noqa: E402

T, KOK = bv.T, bv.KOK
BAS, SON = "<!-- BEGIN:SEKIL (generated by scripts/derle.py from assets/tanim.json - do not edit by hand) -->", "<!-- END:SEKIL -->"
DOSYA_GRUPLARI = [("bolumler-1-2.md", ["1", "2"], "General and Functional"), ("bolumler-3.md", ["3"], "Technical"),
                  ("bolumler-4-5.md", ["4", "5"], "SAP Objects, Errors and Authorization"), ("bolumler-6-7.md", ["6", "7"], "Test and Operations")]


def bolum_dosyasi(gruplar, ad):
    out = [f"# Section writing guide · {ad}", "",
           "Generated file (source: assets/tanim.json). Column numbers start at 0 and follow the array order in the JSON. "
           "{X-nn} is the row id; [a | b] takes only these values; (KARAR) = do not decide yourself, mark it when the inputs do not state it.", ""]
    for b in T["bolumler"]:
        if b["grup"] in gruplar:
            out += [bv.bilgi_metni(b, ornek=True), "Good practice: " + b["pratik"], ""]
    return "\n".join(out).rstrip() + "\n"


def yazim():
    out = ["# Writing rules", "", "Generated file (source: assets/tanim.json).", "",
           "## Cell and id rules", "",
           "- Every cell is a non-empty string; `—` means none.",
           "- Ids have the form `PREFIX-nn`, two digits, unique across the document.",
           "- Several ids are listed one by one, comma-separated: `STEP-01, STEP-02`. A range (`STEP-01…06`) is invalid.",
           "- A section refers to another section only by id. Chain: REQ → SC → STEP → OBJ / MAP / MSG → TC.",
           "- In 3.5 a step that uses mappings cites the MAP ids and a step that raises an error cites the MSG id; 4.1 'Kullanıldığı yer' cites STEP / MAP / UI ids. "
           "6.2 is derived from these references.", "",
           "## Markers", "",
           f"- Missing decision: `{T['isaretler']['karar']} (OPEN-nn)` · missing fact: `{T['isaretler']['bilgi']} (OPEN-nn)`. Option columns may carry a marker too. "
           "An unknown fact is never filled with a default value (`Hayır`, `Must`, an invented date).",
           "- A 7.3 row carries no marker. Owner: a name, or a role when unknown. Target date: when given; otherwise `—`, never invented. Status `Açık`. "
           "The row a KARAR marker points to gets the category `Karar bekleyen konu`; other rows get the fitting readiness item or `—`.",
           "- Decision and fact markers tied to the same question may share one OPEN-nn; the row's category is then `Karar bekleyen konu`.",
           "- The known part of a cell is written; only the unknown part gets a marker: `HTTP POST; zaman aşımı KARAR BEKLİYOR (OPEN-03)`.",
           "- When a section that cannot be switched off waits entirely on one decision, write its minimum number of rows; known cells as text, "
           "decision-dependent cells as markers. Marker rows are not multiplied.",
           f"- An SAP standard object name found neither in the inputs nor in the project catalog is written only in 4.1 with ` {T['isaretler']['dogrula']}` appended; "
           "one open point in 7.3 covers all such names.",
           "- Custom (Z/Y) names may be proposed according to the project naming rule.", "",
           "## Readiness penalty categories (7.3)", "", "| Category | When |", "|---|---|"]
    out += [f"| {k} | {T['hazirlik_anlamlari'][k]} |" for k in T["hazirlik_kalemleri"]]
    out += ["| — | None fits (for example only a date or an owner name is awaited) |", "",
            "## EARS requirement patterns (2.2)", "", "| Pattern | Syntax | Example |", "|---|---|---|"]
    out += [f"| {e['kalip']} | {e['soz_dizimi']} | {e['ornek']} |" for e in T["ears"]]
    out += ["", "The acceptance criterion has the form Given – When – Then: precondition and test data · triggering event · observable result and where it is observed.", "",
            "## Concrete replacement instead of a vague phrase", "", "| Do not write | Write instead |", "|---|---|"]
    out += [f"| {x['yazma']} | {x['yaz']} |" for x in T["yuvarlak_karsiliklar"]]
    out += ["", "Patterns the validator looks for: " + ", ".join(f"`{x.strip()}`" for x in T["yuvarlak_ifadeler"]) + ".", "",
            "## Concreteness", "",
            "- A measure instead of an adjective: duration, count, volume, retention period, retry count are written with a number and a unit.",
            "- Object and field names are written: `I_PurchaseOrderAPI01.PurchaseOrder`; never 'ilgili tablo'.",
            "- Test data has a real format: document number, master data number, company code.",
            "- In RAP, persistence happens inside the save sequence; `COMMIT WORK` is not written."]
    return "\n".join(out) + "\n"


def denetim():
    P = T["parametreler"]
    out = ["# Mechanical validation and indicator", "", "Generated file (source: assets/tanim.json). When code can run, `scripts/bv.py denetle` is authoritative; "
           "otherwise the list below is applied by hand.", "",
           "## Scoring engine rules (mechanical counterparts)", "", "| Rule | Requires | Weight | Severity | Section |", "|---|---|---|---|---|"]
    out += [f"| {k['id']} | {k['baslik']} | {k['agirlik']} | {k['siddet']} | {'all' if k['bolumler'] == ['*'] else ', '.join(k['bolumler'])} |" for k in T["kurallar"]]
    out += ["", "Legacy engine rules (reported separately, not part of the indicator): " + " · ".join(f"{k['id']} {k['baslik']} ({k['bolum']})" for k in T["eski_kurallar"]) + ".", "",
            "## The skill's own checks", "",
            "| Rule | Severity | What it checks |", "|---|---|---|",
            "| YAPI_001–009 | error / warning | Schema version, type and profile, undefined section or field, row length, option values, id format, duplicate id |",
            "| KRITIK_001 | error | A critical section cannot be switched off |",
            "| ZINCIR_001 | error | Every cited id must be defined |",
            "| ZINCIR_002 | warning | Every REQ needs at least one SC, STEP and TC |",
            "| UYD_001 | error | An SAP standard object name must appear in the inputs or the project catalog, or be marked `[DOĞRULANACAK]` |",
            "| UYD_002 | warning | Objects to verify need an open point in 7.3 |",
            "| KARAR_001 | warning | A BEKLİYOR marker must carry an OPEN-nn |",
            "| KARAR_002 | warning | An open point cited by a KARAR marker needs a readiness category |",
            "| OPEN_001 | warning / info | An open point needs an owner (name or role; a defect). Rows without a target date count as waiting for input |",
            "| OPEN_002 | warning | 7.3 'Etkilediği bölüm' must contain section numbers valid in this document |",
            "| ZINCIR_003 | info | Every message of type E or A needs a test case |",
            "| YAPI_010 | warning | meta, surum_gecmisi and onaylar cells must be filled (— when none) |", "",
            "## Defects and waiting for input", "",
            "`denetle` returns two kinds of result. **Defect**: a finding caused by the writing, to be fixed. **Waiting for input**: the rule fails only because a cell waits for a decision "
            "or a fact; the indicator counts it, but there is nothing to fix and no content is invented. The exit code is 1 only for defect-level errors.", "",
            "## Manual checklist (when code cannot run)", "",
            "1. No `«…»`, TBD, TODO or empty cell; `—` when none.", "2. 2.5 has Bağımlılık, Varsayım and Kapsam dışı; the scope boundary is written.",
            "3. 2.1 has a problem step marked 'Evet' with a numeric effect.", "4. No vague phrases in 2.2 and 3.5.",
            "5. 3.5 has at least 3 steps; most steps name an SAP object; error → MSG and commit/rollback are written.",
            "6. Every 3.4 row has source, target, type and example value.", "7. 5.1 has at least 2 rows; type E/W/I/S/A.",
            "8. 6.1 has at least 2 cases; at least one Negatif or Sınır; the test data contains real-format numbers.",
            "9. 5.2 / 5.3 rows have object, field-value, activity and catalog names.",
            "10. Every object named in other sections is in 4.1; every 4.1 name appears in another section; the type is from the list; Z names follow the rule.",
            "11. Every cited id is defined; every REQ has SC, STEP and TC.",
            "12. Every BEKLİYOR marker and every `[DOĞRULANACAK]` maps to a 7.3 row; open rows have an owner (name or role) and affected section numbers.", "",
            "## Indicator", "",
            "Computed from mechanical rules only; the real engine scores quality (LLM part). A by-product, not a target.", "",
            f"- Section rule score = 100 × (1 − remaining rule weight / evaluated rule weight); `info` rule × {P['info_factor']}; "
            f"at most {P['error_cap']} when an `error` rule remains.",
            "- Average = weighted average over applicable base sections and written bonus sections.",
            f"- Penalties: every critical section below {P['crit_thr']} −{P['crit_pen']}; if the 2 lowest base sections are {P['weak_gap1']}+ below the average "
            f"−{P['weak_pen1']}, {P['weak_gap2']}+ below −{P['weak_pen2']} (at most −{P['weak_cap']}); every categorised open point in 7.3 −{P['ready_per']} "
            f"(at most −{P['ready_item_cap']} per item, −{P['ready_cap']} in total).",
            f"- Bands: ≥ {P['band_hi']} Geliştirmeye hazır · {P['band_mid']}–{P['band_hi'] - 1} Koşullu · < {P['band_mid']} Revizyon.",
            "- " + T["parametre_notu"]]
    return "\n".join(out) + "\n"


def sema():
    isaret = {"type": "string", "pattern": "BEKLİYOR"}
    bolumler = {}
    for b in T["bolumler"]:
        if b.get("turetilmis"):
            continue
        dolu = {"type": "object", "additionalProperties": False, "properties": {"mermaid": {"type": "string"}}}
        if b["alanlar"]:
            dolu["properties"]["alanlar"] = {"type": "object", "additionalProperties": False, "required": [a["anahtar"] for a in b["alanlar"]],
                                            "properties": {a["anahtar"]: {"type": "string", "minLength": 1} for a in b["alanlar"]}}
            dolu["required"] = ["alanlar"]
        if b["sutunlar"]:
            ogeler = []
            for c in b["sutunlar"]:
                if c.get("secenekler"):
                    ogeler.append({"anyOf": [{"enum": c["secenekler"]}, isaret]})
                elif c.get("kimlik"):
                    ogeler.append({"type": "string", "pattern": "^(" + "|".join(c["kimlik"]) + ")-[0-9]{2,3}$"})
                else:
                    ogeler.append({"type": "string", "minLength": 1})
            dolu["properties"]["satirlar"] = {"type": "array", "minItems": b["en_az_satir"],
                                             "items": {"type": "array", "items": ogeler, "minItems": len(ogeler), "maxItems": len(ogeler)}}
            dolu.setdefault("required", []).append("satirlar")
        gecersiz = {"type": "object", "additionalProperties": False, "required": ["gecerli", "gerekce"],
                    "properties": {"gecerli": {"const": False}, "gerekce": {"type": "string", "minLength": 1}}}
        bolumler[b["no"]] = dolu if b["sinif"] == "Kritik" else {"oneOf": [dolu, gecersiz]}
    dizi = lambda n: {"type": "array", "items": {"type": "array", "items": {"type": "string"}, "minItems": n, "maxItems": n}}
    return {"$schema": "http://json-schema.org/draft-07/schema#", "title": "Belirtim Yazmanı FS-TS içeriği", "type": "object",
            "required": ["sema", "meta", "turler", "profil", "bolumler"], "additionalProperties": False,
            "properties": {"sema": {"const": T["sema"]},
                           "meta": {"type": "object", "required": ["surum", "tarih", "hazirlayan", "durum"],
                                    "properties": {k: {"type": "string"} for k in ("surum", "tarih", "hazirlayan", "durum", "musteri")}},
                           "turler": {"type": "array", "minItems": 1, "uniqueItems": True, "items": {"enum": [t["kod"] for t in T["tur_tanimlari"]]}},
                           "profil": {"enum": list(T["profiller"])},
                           "bolumler": {"type": "object", "additionalProperties": False, "properties": bolumler},
                           "surum_gecmisi": dizi(4), "onaylar": dizi(3), "nesne_degil": {"type": "array", "items": {"type": "string"}}}}


SEKIL_METIN = {
    "en": {"legend": "Legend: `no title | weight class | types | fields | columns`. Class K = Kritik, N = Normal, B = Bonus (bonus sections open by profile). "
                     "Types: {turler}; `*` = all. "
                     "Column 0 written as `{{X}}` is the row ID `X-nn`; `{{A/B/C}}` = one of these prefixes, by row kind. `[a|b]` after a column = only these values; "
                     "after a field = preferred wording (when none fits, write the stated decision in its own words). "
                     "`†` = a decision: write it only when the inputs state it or a stated decision determines it completely; otherwise a KARAR marker.",
           "derived": "derived by the script - never write", "min": " (min {n} rows)", "all": "all", "tam": "tam only",
           "bonus": "Bonus sections opened in profile `standart`: {liste}. Profile `hafif` opens only 6.2; `tam` opens all.",
           "n54": "5.4 lists only the extra columns; message class, type and TR text are joined from 5.1 by MSG id.",
           "n34": "5.2 and 5.3 share one AUTH sequence. 3.4 for type U without an external interface maps source (CDS / API field) to service entity property: "
                  "`yon` and `comm_scenario` are `—`, `protokol` is the OData version of 1.2, `tetikleyici` is the user action."},
}


def sekil(dil="en"):
    M = SEKIL_METIN.get(dil, SEKIL_METIN["en"])
    out = [BAS, M["legend"].format(turler=", ".join(f"{t['kod']} = {t['ad']}" for t in T["tur_tanimlari"])), ""]
    for b in T["bolumler"]:
        alanlar = ", ".join(a["anahtar"] + ("†" if a.get("karar") else "") + (" [" + "|".join(a["secenekler"]) + "]" if a.get("secenekler") else "")
                            for a in b["alanlar"]) or "—"
        if b.get("turetilmis"):
            sutunlar = M["derived"]
        elif not b["sutunlar"]:
            sutunlar = "—"
        else:
            sutunlar = "; ".join(("{" + "/".join(c["kimlik"]) + "}" if c.get("kimlik") else c["ad"])
                                 + (" [" + "|".join(c["secenekler"]) + "]" if c.get("secenekler") else "") + ("†" if c.get("karar") else "")
                                 for c in b["sutunlar"])
        ek = M["min"].format(n=b["en_az_satir"]) if b["en_az_satir"] > 1 else ""
        out.append(f"{b['no']} {b['baslik']} | {b['agirlik']} {b['sinif'][0]} | {','.join(b['turler'])} | {alanlar} | {sutunlar}{ek}")
    liste = ", ".join(f"{b['no']} ({M['all'] if '*' in b['bonus_acilis'] else '/'.join(b['bonus_acilis']) or M['tam']})"
                      for b in T["bolumler"] if b["sinif"] == "Bonus")
    out += ["", M["bonus"].format(liste=liste), M["n54"], M["n34"], SON]
    return "\n".join(out)


def hedefler():
    h = {os.path.join("references", d): bolum_dosyasi(g, ad) for d, g, ad in DOSYA_GRUPLARI}
    h[os.path.join("references", "yazim.md")] = yazim()
    h[os.path.join("references", "denetim.md")] = denetim()
    h[os.path.join("assets", "icerik-semasi.json")] = json.dumps(sema(), ensure_ascii=False, indent=1) + "\n"
    skill = os.path.join(KOK, "SKILL.md")
    if os.path.exists(skill):
        s = open(skill, encoding="utf-8").read()
        if BAS in s and SON in s:
            dil = re.search(r'(?m)^\s*language:\s*"?(tr|en)"?\s*$', s[:s.index(BAS)])
            # Instructions are English in both language packages; the shape block always uses the English legend.
            h["SKILL.md"] = s[:s.index(BAS)] + sekil("en") + s[s.index(SON) + len(SON):]
    return h


def main():
    kontrol = "--kontrol" in sys.argv
    fark = []
    for yol, icerik in hedefler().items():
        tam = os.path.join(KOK, yol)
        mevcut = open(tam, encoding="utf-8").read() if os.path.exists(tam) else None
        if mevcut != icerik:
            fark.append(yol)
            if not kontrol:
                os.makedirs(os.path.dirname(tam), exist_ok=True)
                with open(tam, "w", encoding="utf-8", newline="\n") as f:  # LF on every platform
                    f.write(icerik)
    if kontrol:
        print("Derived files are up to date." if not fark else "Out of date: " + ", ".join(fark) + " → python scripts/derle.py")
        sys.exit(1 if fark else 0)
    print("Written: " + (", ".join(fark) if fark else "no change"))


if __name__ == "__main__":
    main()
